
.travis.yml:

language: node_js
node_js:
  - "5"
  - "4.2"
before_script:
  - npm install -g mocha
  - npm install
  - mysql -u root -e 'create database travis_db;'
  - mysql -u root travis_db < tables.sql

script: mocha
